name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: public
          path: public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:hub-folder-name-generator
        env:
          FIREBASE_TOKEN: ${{ secrets.06B8qhoAVQnKUCgYIARAAGAYSNwF-L9IrSEjeM5m1k8Mq2DaE5clHs3tcax_3a9Rdi65L44622rCep6PES22DAVvmoQmFhyjyGjk }}